-
  name: Started Docker Installation
  hosts: all
  vars_prompt:
    - name: nightly
      prompt: "Do you want enable docker nightly repo(optional) [yes/no]"
      private: no
    - name: test
      prompt: "Do you want enable docker test repo(optional) [yes/no]"
      private: no
  tasks:
    - include_vars: ../variable/vars.yml
    - name: Remove old versions of Docker
      yum: pkg={{item}} state=absent
      with_items:
       - docker
       - docker-client
       - docker-client-latest
       - docker-common
       - docker-latest
       - docker-latest-logrotate
       - docker-logrotate
       - docker-engine
    - name: Install Yum - Utills
      yum:
       name: yum-utils
       state: present
    - name: Enable Docker Repo For Docker Installation
      shell: |
       yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Enabled Docker Test Repository
      shell: |
       yum-config-manager --enable docker-ce-test
      when: nightly == "yes"
    - name: Enabled Docker Nightly Repository
      shell: |
       yum-config-manager --enable docker-ce-nightly
      when: test == "yes"
    - name: Install Docker Packages
      shell: |
       yum install docker-ce docker-ce-cli containerd.io -y
      #yum:
      # name:
      #  - container-selinux
      #  - docker-ce
      #  - docker-ce-cli
      #  - containerd.io
      # state: present
    - name: Enable Docker Service And Start
      shell: |
       systemctl enable docker
       systemctl start docker
       systemctl status docker