-
  name: Started Preparing Of K8s cluster
  hosts: all
  tasks:
    - include_vars: ../variable/vars.yml
    - name: Closing Selinux, Swap and Firewalld
      shell: |
       swapoff -a
       sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
       setenforce 0
       sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' {{selinux}}
       systemctl stop firewalld
       systemctl disable firewalld
    - name: Copying Kubernetes Repo file
      copy:
       src: ../files/kubernetes.repo
       dest: /etc/yum.repos.d/kubernetes.repo
       mode: '0644'
    - name: Install And Enable Kubelet
      shell: |
       yum install -y kubelet-1.21.3 kubeadm-1.21.3 kubectl-1.21.3 --disableexcludes=kubernetes
       CG=$(sudo docker info 2>/dev/null | sed -n 's/Cgroup Driver: \(.*\)/\1/p')
       sed -i 's/KUBELET_EXTRA_ARGS=.*/KUBELET_EXTRA_ARGS=--cgroup-driver='"$CG"'/g' /etc/sysconfig/kubelet
       sed -i 's/[[:blank:]]*=[[:blank:]]*/=/g' /etc/sysconfig/kubelet
       systemctl enable kubelet
       systemctl start kubelet
       bash -c 'cat <<EOF >  /etc/sysctl.d/k8s.conf
       net.bridge.bridge-nf-call-ip6tables = 1
       net.bridge.bridge-nf-call-iptables = 1
       EOF'
       sysctl --system
       lsmod | grep br_netfilter